<a href="https://colab.research.google.com/github/vinigm/Estudos/blob/main/Matematica_e_Estatistica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Vetorização de Problemas**
---



**Abordagens Estatísticas**
- Descritiva: foco no passado para entender o presente
- Preditiva: foca no passado para inferir no futuro

**VETORIZAÇÃO:** Processo de transformar um código escalar em sua forma vetorial. A vantagem de utilizarmos vetorização é que ela é mais rápida e utiliza menos memória

Exemplo 1: Comparar o retorno de cada cliente obtido através do investimento com o valor corrigido pela inflação. Quantos clientes "perderam" para a inflação?

In [1]:
montante = 1000
montante_final = 1001.5 # 0.15% de retorno

In [2]:
ipca = 0.25/100
montante_inflacao = montante * (1+ipca)

print(montante_inflacao)

1002.5


In [3]:
print(montante_final < montante_inflacao)

True


Para 100 mil clientes

In [5]:
from random import random, randint
montante_lista = [randint(0,5000) for _ in range(0,100000)]
montante_final_lista = [round(montante * (1+ (0.3 * random() / 100)), 2) for montante in montante_lista]                       

In [7]:
print(montante_lista[0:5])
print(montante_final_lista[0:5])

[2014, 3196, 2343, 4568, 4317]
[2017.02, 3199.53, 2348.13, 4578.14, 4322.08]


In [12]:
from time import time

perdeu = list()

inicio = time()
for montante, montante_final in zip(montante_lista, montante_final_lista):
  perdeu.append(montante_final - montante * (1 + ipca))
fim = time()

perdeu = list(filter(lambda val: True if val < 0 else False, perdeu))
print(f'{len(perdeu)} cliente perderam para a inflação')

tempo_lista = fim - inicio
print(tempo_lista)

83140 cliente perderam para a inflação
0.03198957443237305


**PACOTE NUMPY**

Vamos vetorizar nosso calculo através da criação de vetores NumPy

In [13]:
import numpy as np

montante_array = np.array(montante_lista)
montante_final_array = np.array(montante_final_lista)

In [14]:
print(montante_array)
print(montante_final_array)

[2014 3196 2343 ... 1436 4144  547]
[2017.02 3199.53 2348.13 ... 1437.85 4144.15  548.3 ]


In [17]:
from time import time

inicio = time()
perdeu = montante_final_array - montante_array * (1 + ipca)
fim = time()

perdeu = list(filter(lambda val: True if val < 0 else False, perdeu))
print(f"{len(perdeu)} cliente eprderam para a inflação")

tempo_array = fim - inicio
print(f"Duração: {tempo_array}")


83140 cliente eprderam para a inflação
Duração: 0.0023941993713378906


Comparando os tempos de execução das operações escalares e vetoriais

In [19]:
tempo_lista / tempo_array # Vemos assim que fazendo através de vetorização aumentamos o tempo de processamento 13x

13.361282613025294

# **Introdução ao NumPy**

---



**Arrays vs Listas**

Ambos servem para armazenar dados sequencialmente na memória, contudo é importante maximizar suas diferenças:

- Manipulação algébrica: Arrays apresentam uma sintaxe mais simples e eficiente
- Listas sempre trabalham de forma escalar

Exemplo escalar:

In [2]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]

l3 = [a + b for a, b in zip(l1, l2)]
print(l3)

[5, 7, 9]


Exemplo vetorial:

In [3]:
import numpy as np

a1 = np.array(l1)
a2 = np.array(l2)

a3 = a1 + a2
print(a3)

[5 7 9]


- Tipo: arrays trabalham melhor com elementos do mesmo tipo
- Mutabilidade: arrays são menos eficientes quanto a inserção e remoção de elementos

**Arrays 1D: Vetores**

Arrays NumPy de uma dimensão são conhecidos como **vetores**, como listas, de uma linha e uma ou mais colunas.

Criação:

In [5]:
a1 = np.array([2, 4, 6, 8])
print(a1)

[2 4 6 8]


In [7]:
a1 = np.arange(0, 10, 2)
print(a1)

[0 2 4 6 8]


In [10]:
a1 = np.zeros(10)
print(a1)

a1 = 10 * np.ones(10)
print(a1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


Manipulação:

In [11]:
a1 = np.array([2,4,6,8])
print(a1)

[2 4 6 8]


In [13]:
a1[0]

array([6, 8])

In [14]:
a1[0:2]

array([2, 4])

In [15]:
a1[a1>4]

array([6, 8])

Atributos:

In [16]:
a1.ndim

1

In [17]:
a1.shape

(4,)

In [18]:
a1.size

4

In [19]:
a1.dtype

dtype('int64')

Metodos:

In [20]:
a1.sort() # "inplace"
print(a1)

[2 4 6 8]


In [21]:
a1.tolist()

[2, 4, 6, 8]

**Arrays 2D: Matrizes**

Arrays NumPy de duas dimensões são conhecidos como **matrizes**, como tabelas, com linhas e colunas.

Criação:

In [23]:
m1 = np.array([[1,2,3], [4,5,6]]) # vetores como linhas
print(m1)

[[1 2 3]
 [4 5 6]]


ManipulaçãO:

In [24]:
m1[1,2]

6

In [25]:
m1[1,:]

array([4, 5, 6])

In [26]:
m1[:,1]

array([2, 5])

Atributos:

In [27]:
m1.ndim

2

In [28]:
m1.shape

(2, 3)

In [29]:
m1.dtype

dtype('int64')

In [30]:
m1.sort()
print(m1)

[[1 2 3]
 [4 5 6]]


In [31]:
m1.tolist()

[[1, 2, 3], [4, 5, 6]]